import { useEffect, useMemo, useState } from 'react';
import { categories, findServices, Service, services } from './services';

type Screen='home'|'loading'|'results'|'fallback'|'flow'|'done'|'saved'|'auth';
type SavedInfo={label:string;value:string;source:string};
type Account={id:string;name:string;phone:string};
const mockAccounts:Account[]=[{id:'aarav',name:'Aarav Sharma',phone:'•••• 4488'},{id:'meera',name:'Meera Sharma',phone:'•••• 7712'}];
const examples=['I lost my Aadhaar card','I need to renew my driving licence','How can I check my PF balance?','I want to apply for a birth certificate','My ration card needs an update'];
const labels:Record<string,string>={aadhaar:'e-Aadhaar download','aadhaar-request':'Aadhaar replacement',pf:'PF passbook check',licence:'Driving licence renewal',birth:'Birth certificate request',ration:'Ration card update',generic:'Service request'};
const flowSteps:Record<string,string[]>={aadhaar:['Your details','Verify mobile'],'aadhaar-request':['Your details','Verify mobile','Review & submit'],pf:['Your UAN','Verify mobile'],licence:['Licence details','Documents','Review & submit'],birth:['Birth details','Documents','Review & submit'],ration:['Household details','Documents','Review & submit'],generic:['Your details','Review & submit','Confirmation']};
const needSummaries:Record<string,string>={'aadhaar-lost-card':'requesting a replacement after losing your Aadhaar card','eaadhaar':'downloading a digital Aadhaar copy','pf-passbook':'checking your PF balance and passbook','dl-renew':'renewing your driving licence','birth-apply':'applying for a birth certificate','birth-download':'getting an existing birth certificate','ration-update':'updating your ration-card household details'};

export function App(){
 const [screen,setScreen]=useState<Screen>('home'),[query,setQuery]=useState(''),[matches,setMatches]=useState<ReturnType<typeof findServices>>([]),[selected,setSelected]=useState<Service|null>(null),[step,setStep]=useState(0),[font,setFont]=useState(16),[contrast,setContrast]=useState(false),[lang,setLang]=useState('English'),[saved,setSaved]=useState(false),[uploaded,setUploaded]=useState<string[]>([]),[otp,setOtp]=useState(''),[account,setAccount]=useState<Account|null>(null),[savedByAccount,setSavedByAccount]=useState<Record<string,SavedInfo[]>>({});
 const flow=selected?flowSteps[selected.flow]:[];
 const savedInfo=account?savedByAccount[account.id]||[]:[];
 const reference=useMemo(()=>`SRTH-${selected?.id?.slice(0,3).toUpperCase()||'REQ'}-260828`,[selected]);
 useEffect(()=>{document.documentElement.style.setProperty('--font',`${font}px`); document.body.dataset.contrast=String(contrast)},[font,contrast]);
 function submit(value=query){const found=findServices(value);setQuery(value);setMatches(found);setScreen('loading');setTimeout(()=>setScreen(found[0]?.score>=3?'results':'fallback'),700)}
 function choose(s:Service){setSelected(s);setStep(0);setUploaded([]);setOtp('');setSaved(false);setScreen('flow')}
 function advance(){if(step<flow.length-1){setStep(step+1);setSaved(true)}else setScreen('done')}
 function saveInfo(label:string,value:string){if(!value.trim()||!selected||!account)return;setSavedByAccount(current=>({...current,[account.id]:[...(current[account.id]||[]).filter(item=>item.label!==label),{label,value:value.trim(),source:selected.name}]}))}
 return <main className="shell">
  <header><button className="brand" onClick={()=>setScreen('home')} aria-label="Go to Saarthi home"><span>✦</span> Saarthi</button><div className="tools"><button onClick={()=>setScreen(account?'saved':'auth')}>{account?'My info':'Sign in'}</button>{account&&<button onClick={()=>setAccount(null)} aria-label="Sign out">Sign out</button>}<select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value)}><option>English</option><option>हिंदी</option><option>Hinglish</option></select><button aria-label="Decrease text size" onClick={()=>setFont(Math.max(14,font-2))}>A−</button><button aria-label="Increase text size" onClick={()=>setFont(Math.min(21,font+2))}>A+</button><button aria-pressed={contrast} onClick={()=>setContrast(!contrast)}>◐</button></div></header>
  <div className="notice">Prototype — uses simulated data. Saarthi is independent and not an official government service.</div>
  {screen==='home'&&<Home query={query} setQuery={setQuery} submit={submit} lang={lang}/>} 
  {screen==='loading'&&<section className="state"><div className="spinner"/><h1>Finding the right service…</h1><p>Matching your words with a small, local service guide.</p></section>}
  {screen==='results'&&<Results query={query} matches={matches} choose={choose} onBack={()=>setScreen('home')}/>}
  {screen==='fallback'&&<Fallback query={query} choose={choose} retry={()=>setScreen('home')}/>} 
  {screen==='flow'&&selected&&<Flow service={selected} steps={flow} step={step} otp={otp} setOtp={setOtp} uploaded={uploaded} setUploaded={setUploaded} saved={saved} savedInfo={savedInfo} saveInfo={saveInfo} back={()=>step?setStep(step-1):setScreen('results')} next={advance}/>} 
  {screen==='done'&&selected&&<Done service={selected} reference={reference} home={()=>setScreen('home')}/>} 
  {screen==='saved'&&account&&<SavedInfoPage account={account} items={savedInfo} update={(label,value)=>setSavedByAccount(all=>({...all,[account.id]:(all[account.id]||[]).map(item=>item.label===label?{...item,value}:item)}))} remove={label=>setSavedByAccount(all=>({...all,[account.id]:(all[account.id]||[]).filter(item=>item.label!==label)}))} home={()=>setScreen('home')}/>} 
  {screen==='auth'&&<AuthPage signIn={user=>{setAccount(user);setScreen('home')}} home={()=>setScreen('home')}/>} 
  <footer><span className="online">●</span> Lightweight mode · Works with sample data offline</footer>
 </main>
}
function Home({query,setQuery,submit,lang}:{query:string;setQuery:(v:string)=>void;submit:(v?:string)=>void;lang:string}){return <section className="hero"><h1>{lang==='हिंदी'?'आपको किस काम में मदद चाहिए?':lang==='Hinglish'?'Aapko kis kaam mein madad chahiye?':'What do you need help with?'}</h1><p>Tell us in your own words. We’ll suggest a simple next step.</p><div className="ask"><textarea value={query} onChange={e=>setQuery(e.target.value)} placeholder="For example: I lost my Aadhaar card" aria-label="Describe what you need help with"/></div><button className="primary wide" disabled={!query.trim()} onClick={()=>submit()}>Find my service <span>→</span></button><p className="example-title">Try an example</p><div className="chips">{examples.map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div><div className="reassure"><span>🔒</span><div><b>Your privacy matters</b><br/>Never enter real Aadhaar, bank details, passwords, payments, or OTPs here.</div></div></section>}
function Results({query,matches,choose,onBack}:{query:string;matches:ReturnType<typeof findServices>;choose:(s:Service)=>void;onBack:()=>void}){const top=matches[0];const alts=matches.slice(1,3);const summary=needSummaries[top.service.id]||top.service.description.toLowerCase();return <section><button className="textbtn" onClick={onBack}>← Change my question</button><p className="eyebrow">We found a likely path</p><h1>Sounds like you need help with <em>{summary}.</em></h1><p className="restatement">Start with this. It is the closest match from our simulated service guide.</p><ServiceCard service={top.service} primary choose={choose}/>{alts.length>0&&<><h2>Also possibly useful</h2>{alts.map(m=><ServiceCard key={m.service.id} service={m.service} choose={choose}/>)}</>}<p className="quiet">Not quite right? Go back and use different words. Saarthi will say when it needs more detail.</p></section>}
function ServiceCard({service,choose,primary=false}:{service:Service;choose:(s:Service)=>void;primary?:boolean}){return <article className={'service '+(primary?'best':'')}><div className="service-top"><span className="tag">{primary?'Best match':'Alternative'}</span><span className="channel">{service.channel}</span></div><h2>{service.name}</h2><p>{service.description}</p><div className="facts"><span>◷ {service.time}</span><span>⌂ {service.category}</span></div><details><summary>What you’ll need</summary><p><b>Eligibility:</b> {service.eligibility}</p><p><b>Documents:</b> {service.documents.join(' · ')}</p></details><button className={primary?'primary wide':'secondary wide'} onClick={()=>choose(service)}>Guide me through this <span>→</span></button></article>}
function Fallback({query,choose,retry}:{query:string;choose:(s:Service)=>void;retry:()=>void}){return <section><button className="textbtn" onClick={retry}>← Try another question</button><p className="eyebrow">A little more detail would help</p><h1>We’re not certain what service fits “{query}”.</h1><p>Choose a life event below, or try one of these clearer requests.</p><div className="chips suggestions">{['I need a certificate','I need help with a pension','I have a transport problem'].map(x=><button key={x} onClick={()=>retry()}>{x}</button>)}</div><h2>Browse by life event</h2><div className="categories">{categories.map(c=><button key={c} onClick={()=>choose(services.find(s=>s.category===c)!)}><span>{({ 'Identity & documents':'▣','Jobs & pension':'⌁','Health':'✚','Education':'▤','Travel & transport':'◈','Family & certificates':'♡','Money & benefits':'₹','Housing & utilities':'⌂'} as Record<string,string>)[c]}</span>{c}<small>{services.find(s=>s.category===c)?.description}</small></button>)}</div></section>}
function Flow({service,steps,step,back,next,saved,uploaded,setUploaded,otp,setOtp,savedInfo,saveInfo}:{service:Service;steps:string[];step:number;back:()=>void;next:()=>void;saved:boolean;uploaded:string[];setUploaded:(x:string[])=>void;otp:string;setOtp:(x:string)=>void;savedInfo:SavedInfo[];saveInfo:(label:string,value:string)=>void}){const title=steps[step]; const isOtp=title==='Verify mobile'; const isDocs=title==='Documents'; const isFinal=title==='Review & submit'; const action=isFinal?'Submit request':service.flow==='aadhaar'&&isOtp?'Download e-Aadhaar':service.flow==='pf'&&isOtp?'View passbook':'Save & continue'; return <section className="flow"><button className="textbtn" onClick={back}>← Back</button><div className="progress-label"><span>{labels[service.flow]}</span><span>Step {step+1} of {steps.length}</span></div><div className="progress">{steps.map((s,i)=><span key={s} className={i<=step?'active':''}/>)}</div><h1>{title}</h1>{isOtp?<Otp otp={otp} setOtp={setOtp}/>:isDocs?<Documents uploaded={uploaded} setUploaded={setUploaded}/>:isFinal?<Review service={service} uploaded={uploaded} savedInfo={savedInfo}/>:<FormStep service={service} step={step} savedInfo={savedInfo} saveInfo={saveInfo}/>}<div className="nav"><button className="secondary" onClick={back}>Back</button><button className="primary" onClick={next} disabled={isOtp&&otp.length!==6}>{action} →</button></div></section>}
function StoredField({label,placeholder,savedInfo,saveInfo}:{label:string;placeholder:string;savedInfo:SavedInfo[];saveInfo:(label:string,value:string)=>void}){const [value,setValue]=useState('');const stored=savedInfo.find(item=>item.label===label);return <label>{label}<span className="field-input"><input value={value} placeholder={placeholder} onChange={e=>setValue(e.target.value)} onBlur={e=>saveInfo(label,e.target.value)}/>{stored&&stored.value!==value&&<button type="button" className="autofill" onClick={()=>{setValue(stored.value);saveInfo(label,stored.value)}}>Use saved</button>}</span>{stored&&stored.value!==value&&<small>Saved information is available</small>}</label>}
function FormStep({service,step,savedInfo,saveInfo}:{service:Service;step:number;savedInfo:SavedInfo[];saveInfo:(label:string,value:string)=>void}){const field=(label:string,placeholder:string)=><StoredField label={label} placeholder={placeholder} savedInfo={savedInfo} saveInfo={saveInfo}/>;if(service.flow==='pf'&&step===0)return <>{field('UAN','Example: 1000 2222 3333')}{field('Name','Example: Aarav Sharma')}</>;if(service.flow==='licence')return <>{field('Driving licence number','Example: DL-11-20990001234')}<label>Renewal reason<select><option>Licence expires soon</option><option>Licence already expired</option></select></label></>;if(service.flow==='birth')return <>{field('Child’s name','Example: Meera Sharma')}{field('Date of birth','Example: 2026-05-12')}{field('Place of birth','Example: Sunrise Hospital, Pune')}</>;if(service.flow==='ration')return <>{field('Ration card number','Example: MH-RA-88001234')}<label>Change needed<select><option>Add a household member</option><option>Remove a household member</option><option>Correct a name</option></select></label>{field('Member’s name','Example: Kavya Sharma')}</>;return <>{field('Reference detail','Example: XX11 2233 4455')}{field('Name','Example: Aarav Sharma')}</>}
function Otp({otp,setOtp}:{otp:string;setOtp:(x:string)=>void}){return <><p>We have sent an OTP to the number ending in 4488.</p><label>Enter 6-digit OTP<input inputMode="numeric" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="6-digit OTP"/></label></>}
function Documents({uploaded,setUploaded}:{uploaded:string[];setUploaded:(x:string[])=>void}){const samples=['Sample address proof.pdf','Sample identity proof.jpg','Sample supporting record.pdf'];return <><p>Select safe sample files to see how upload works. No real document can be uploaded.</p><div className="uploads">{samples.map(d=><button key={d} className={uploaded.includes(d)?'picked':''} onClick={()=>setUploaded(uploaded.includes(d)?uploaded.filter(x=>x!==d):[...uploaded,d])}><span>▤</span>{uploaded.includes(d)?'Selected: ':'Select '}{d}</button>)}</div><div className="sample">Files stay in this browser session only.</div></>}
function Review({service,uploaded,savedInfo}:{service:Service;uploaded:string[];savedInfo:SavedInfo[]}){const name=savedInfo.find(item=>item.label==='Name')?.value||'Not provided';return <div className="review"><h2>Ready to submit?</h2><p>You are submitting a simulated request for <b>{service.name}</b>.</p><dl><dt>Applicant</dt><dd>{name}</dd><dt>Channel</dt><dd>{service.channel}</dd><dt>Documents</dt><dd>{uploaded.length?uploaded.join(', '):'No sample files selected'}</dd><dt>Expected time</dt><dd>{service.time}</dd></dl><div className="simulated">This will not contact a government system or create a real application.</div></div>}
function Done({service,reference,home}:{service:Service;reference:string;home:()=>void}){const retrieval=service.flow==='aadhaar'||service.flow==='pf';const heading=service.flow==='aadhaar'?'Your e-Aadhaar is ready.':service.flow==='pf'?'Your PF passbook is ready.':'You’re all set for now.';return <section className="done"><div className="check">✓</div><p className="eyebrow">{retrieval?'Ready to view':'Request submitted'}</p><h1>{heading}</h1>{retrieval?<article><h2>{service.flow==='aadhaar'?'Mock e-Aadhaar':'Mock PF balance'}</h2><p>{service.flow==='aadhaar'?'A fictional digital Aadhaar copy is available for download.':'Available balance: ₹1,84,620 · Last contribution: July 2026'}</p><button className="secondary wide">{service.flow==='aadhaar'?'Download mock e-Aadhaar':'Open mock passbook'} →</button></article>:<><p>Your simulated reference number is</p><div className="reference">{reference}</div><article><h2>What happens next</h2><p>The relevant department will review your request. Expected processing time for <b>{service.name}</b>: {service.time}.</p></article></>}<button className="primary wide" onClick={home}>Start another request</button></section>}
function SavedInfoPage({account,items,update,remove,home}:{account:Account;items:SavedInfo[];update:(label:string,value:string)=>void;remove:(label:string)=>void;home:()=>void}){const [editing,setEditing]=useState<string|null>(null);return <section><button className="textbtn" onClick={home}>← Back to services</button><h1>My saved info</h1><p className="restatement">Saved for {account.name}. Edit or delete these details at any time. Use synthetic demo data only.</p>{items.length===0?<div className="empty"><h2>Nothing saved yet</h2><p>When you use a service form, entered details will appear here for you to reuse.</p><button className="primary" onClick={home}>Find a service</button></div>:<div className="saved-list">{items.map(item=><article key={item.label}><b>{item.label}</b>{editing===item.label?<input aria-label={`Edit ${item.label}`} value={item.value} onChange={e=>update(item.label,e.target.value)}/>:<p>{item.value}</p>}<div className="saved-actions"><button className="secondary" onClick={()=>setEditing(editing===item.label?null:item.label)}>{editing===item.label?'Save':'Edit'}</button><button className="delete-button" onClick={()=>remove(item.label)}>Delete</button></div></article>)}</div>}</section>}
function AuthPage({signIn,home}:{signIn:(account:Account)=>void;home:()=>void}){return <section className="auth"><button className="textbtn" onClick={home}>← Continue without signing in</button><p className="eyebrow">Prototype sign-in</p><h1>Choose a mock account</h1><p>Signing in lets Saarthi keep your saved information separate from other demo accounts. No password, OTP, or real identity details are used.</p><div className="account-list">{mockAccounts.map(account=><button key={account.id} className="account-card" onClick={()=>signIn(account)}><span className="avatar">{account.name[0]}</span><span><b>{account.name}</b><small>Mobile {account.phone}</small></span><strong>Sign in →</strong></button>)}</div></section>}
