export type Service = { id:string; name:string; category:string; intents:string[]; keywords:string[]; eligibility:string; documents:string[]; time:string; channel:'Online'|'In person'|'Mixed'; flow:'aadhaar'|'aadhaar-request'|'pf'|'licence'|'birth'|'ration'|'generic'; description:string };
export const services: Service[] = [
 {id:'aadhaar-lost-card',name:'Request Aadhaar replacement',category:'Identity & documents',intents:['lost aadhaar','lost aadhaar card'],keywords:['aadhaar','lost','card','replacement'],eligibility:'Anyone whose Aadhaar card has been lost or damaged.',documents:['Aadhaar number or enrolment ID','Mobile number linked to Aadhaar'],time:'7–10 working days',channel:'Online',flow:'aadhaar-request',description:'Request a replacement Aadhaar card after it is lost or damaged.'},
 {id:'eaadhaar',name:'Download e-Aadhaar',category:'Identity & documents',intents:['download aadhaar','aadhaar copy'],keywords:['aadhaar','download','copy','uidai'],eligibility:'Anyone with an Aadhaar number can retrieve a digital copy.',documents:['Aadhaar number or enrolment ID','Mobile number linked to Aadhaar'],time:'About 5 minutes',channel:'Online',flow:'aadhaar',description:'Download a digital Aadhaar copy when you already know your Aadhaar details.'},
 {id:'aadhaar-update',name:'Update Aadhaar details',category:'Identity & documents',intents:['update aadhaar address'],keywords:['aadhaar','update','address','name'],eligibility:'For people whose Aadhaar details need correcting.',documents:['Address or identity proof'],time:'1–2 visits may be needed',channel:'Mixed',flow:'generic',description:'Correct an address, name, or other Aadhaar detail.'},
 {id:'pf-passbook',name:'View EPFO passbook & PF balance',category:'Jobs & pension',intents:['check pf balance','epf balance','pf passbook'],keywords:['pf','epf','epfo','passbook','balance','uan'],eligibility:'EPFO members with an activated UAN.',documents:['UAN','Registered mobile number'],time:'About 3 minutes',channel:'Online',flow:'pf',description:'See your fictional PF balance and contribution history.'},
 {id:'pf-claim',name:'EPFO online claim',category:'Jobs & pension',intents:['withdraw pf','pf claim'],keywords:['withdraw','claim','pf','epf'],eligibility:'Eligible EPFO members with a linked bank account.',documents:['UAN','Bank details','PAN where applicable'],time:'7–20 working days',channel:'Online',flow:'generic',description:'Apply for an EPFO withdrawal or advance.'},
 {id:'dl-renew',name:'Renew driving licence',category:'Travel & transport',intents:['renew driving licence','licence renewal'],keywords:['driving','licence','license','renew','dl'],eligibility:'Holders of an expiring or expired driving licence.',documents:['Current driving licence','Address proof','Medical form if applicable'],time:'7–14 working days',channel:'Mixed',flow:'licence',description:'Start a renewal and book a mock RTO visit if needed.'},
 {id:'dl-status',name:'Check driving licence status',category:'Travel & transport',intents:['driving licence status'],keywords:['driving','licence','status','dl'],eligibility:'Applicants with an application number.',documents:['Application number'],time:'About 2 minutes',channel:'Online',flow:'generic',description:'Check the status of a licence application.'},
 {id:'birth-apply',name:'Apply for a birth certificate',category:'Family & certificates',intents:['apply birth certificate','birth certificate'],keywords:['birth','certificate','newborn','baby'],eligibility:'Parents or authorised relatives of a child.',documents:['Hospital record','Parents’ ID','Address proof'],time:'7–21 working days',channel:'Mixed',flow:'birth',description:'Register a birth and request a certificate.'},
 {id:'birth-download',name:'Download birth certificate',category:'Family & certificates',intents:['get birth certificate'],keywords:['birth','certificate','download','copy'],eligibility:'People with a registered birth record.',documents:['Registration number','Date and place of birth'],time:'About 5 minutes',channel:'Online',flow:'birth',description:'Find or download an existing certificate.'},
 {id:'ration-update',name:'Update ration card household details',category:'Money & benefits',intents:['update ration card','add ration member'],keywords:['ration','card','family','member','household','update'],eligibility:'Existing ration-card holders.',documents:['Ration card','Identity proof','Supporting family document'],time:'15–30 working days',channel:'Mixed',flow:'ration',description:'Add, remove, or correct a household member.'},
 {id:'ration-status',name:'Check ration card status',category:'Money & benefits',intents:['ration card status'],keywords:['ration','status','card'],eligibility:'Applicants with a reference number.',documents:['Application reference'],time:'About 2 minutes',channel:'Online',flow:'generic',description:'Track a ration card request.'},
 {id:'ayushman',name:'Check Ayushman Bharat eligibility',category:'Health',intents:['health card','ayushman eligibility'],keywords:['ayushman','health','hospital','card'],eligibility:'Families listed in eligible records.',documents:['Mobile number','Basic family details'],time:'About 5 minutes',channel:'Online',flow:'generic',description:'Check whether your family may be eligible for health cover.'},
 {id:'vaccination',name:'Find vaccination record',category:'Health',intents:['vaccination certificate'],keywords:['vaccine','vaccination','immunization'],eligibility:'People with a recorded vaccination.',documents:['Registered mobile number'],time:'About 5 minutes',channel:'Online',flow:'generic',description:'Find a vaccination record or certificate.'},
 {id:'scholarship',name:'Find scholarship schemes',category:'Education',intents:['student scholarship'],keywords:['scholarship','student','college','school'],eligibility:'Depends on the chosen scheme.',documents:['Student ID','Income certificate where required'],time:'10–30 minutes',channel:'Online',flow:'generic',description:'Explore education support in simple terms.'},
 {id:'marksheet',name:'Request a duplicate marksheet',category:'Education',intents:['lost marksheet'],keywords:['marksheet','mark sheet','duplicate','exam'],eligibility:'Students with records at the issuing board or university.',documents:['Identity proof','Roll number'],time:'7–14 working days',channel:'Mixed',flow:'generic',description:'Request a replacement academic record.'},
 {id:'pension',name:'Check pension payment status',category:'Jobs & pension',intents:['pension status'],keywords:['pension','retirement','payment'],eligibility:'Pensioners with a PPO number.',documents:['PPO number','Date of birth'],time:'About 3 minutes',channel:'Online',flow:'generic',description:'Check whether a pension payment has been processed.'},
 {id:'income',name:'Apply for income certificate',category:'Money & benefits',intents:['income certificate'],keywords:['income','certificate','salary'],eligibility:'Residents needing proof of household income.',documents:['Identity proof','Income evidence','Address proof'],time:'7–14 working days',channel:'Mixed',flow:'generic',description:'Apply for an income certificate.'},
 {id:'electricity',name:'View electricity bill',category:'Housing & utilities',intents:['electricity bill'],keywords:['electricity','power','bill','meter'],eligibility:'Electricity consumers with an account number.',documents:['Consumer/account number'],time:'About 3 minutes',channel:'Online',flow:'generic',description:'View a utility bill and payment options.'},
 {id:'water',name:'Apply for water connection',category:'Housing & utilities',intents:['water connection'],keywords:['water','connection','utility'],eligibility:'Residents or owners of a serviceable property.',documents:['Address proof','Property document'],time:'10–30 working days',channel:'Mixed',flow:'generic',description:'Start a new water connection request.'},
 {id:'passport',name:'Passport appointment guidance',category:'Travel & transport',intents:['passport'],keywords:['passport','international','travel'],eligibility:'Indian citizens applying for a passport.',documents:['Identity proof','Address proof','Date-of-birth proof'],time:'Appointment dependent',channel:'Mixed',flow:'generic',description:'Prepare for a passport application and appointment.'},
 {id:'pan',name:'Apply for or correct PAN',category:'Identity & documents',intents:['pan card'],keywords:['pan','tax','permanent account'],eligibility:'Individuals requiring a PAN.',documents:['Identity proof','Date-of-birth proof'],time:'7–15 working days',channel:'Online',flow:'generic',description:'Apply for a PAN or correct basic details.'}
];

export function findServices(query:string) { const terms=query.toLowerCase().match(/[a-z]+/g) || []; return services.map(s=>({service:s,score:s.keywords.reduce((n,k)=>n+(query.toLowerCase().includes(k)?3:0),0)+s.intents.reduce((n,i)=>n+(query.toLowerCase().includes(i)?6:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score); }
export const categories=['Identity & documents','Jobs & pension','Health','Education','Travel & transport','Family & certificates','Money & benefits','Housing & utilities'];
